// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class Assignment
{
    public Guid Id { get; set; }

    public string ExaminerId { get; set; }

    public string FilePath { get; set; }

    public string BaremPath { get; set; }

    public DateTime UploadedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AssignmentDistribution> AssignmentDistributions { get; set; } = new List<AssignmentDistribution>();

    public virtual User Examiner { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}