// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class AssignmentDistribution
{
    public Guid Id { get; set; }

    public Guid? AssignmentId { get; set; }

    public string StudentId { get; set; }

    public string LecturerId { get; set; }

    public string AssignedBy { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User AssignedByNavigation { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual User Lecturer { get; set; }

    public virtual User Student { get; set; }
}