// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class Grade
{
    public Guid Id { get; set; }

    public Guid AssignmentId { get; set; }

    public string StudentId { get; set; }

    public double? FinalScore { get; set; }

    public double? BiasPercent { get; set; }

    public string ConfirmBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual User ConfirmByNavigation { get; set; }

    public virtual ICollection<GradeRound> GradeRounds { get; set; } = new List<GradeRound>();

    public virtual ICollection<RegradeRequest> RegradeRequests { get; set; } = new List<RegradeRequest>();

    public virtual User Student { get; set; }
}