// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class GradeRound
{
    public Guid Id { get; set; }

    public Guid? GradeId { get; set; }

    public int? RoundNumber { get; set; }

    public string LecturerId { get; set; }

    public string CoLecturerId { get; set; }

    public double? Score { get; set; }

    public string Note { get; set; }

    public DateTime? GradeAt { get; set; }

    public DateTime? ScheduleAt { get; set; }

    public string MeetingUrl { get; set; }

    public virtual User CoLecturer { get; set; }

    public virtual Grade Grade { get; set; }

    public virtual User Lecturer { get; set; }
}