// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class RegradeRequest
{
    public Guid Id { get; set; }

    public Guid? GradeId { get; set; }

    public string StudentId { get; set; }

    public int? RequestRound { get; set; }

    public string Status { get; set; }

    public DateTime? RequestAt { get; set; }

    public virtual Grade Grade { get; set; }

    public virtual User Student { get; set; }
}