// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class Submission
{
    public Guid Id { get; set; }

    public Guid AssignmentId { get; set; }

    public string StudentId { get; set; }

    public string FilePath { get; set; }

    public DateTime SubmittedAt { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual User Student { get; set; }
}