// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMGSupport.ThangTQ.Repositories.Models;

public partial class User
{
    public string Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string GoogleId { get; set; }

    public string Role { get; set; }

    public string StudentCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AssignmentDistribution> AssignmentDistributionAssignedByNavigations { get; set; } = new List<AssignmentDistribution>();

    public virtual ICollection<AssignmentDistribution> AssignmentDistributionLecturers { get; set; } = new List<AssignmentDistribution>();

    public virtual ICollection<AssignmentDistribution> AssignmentDistributionStudents { get; set; } = new List<AssignmentDistribution>();

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Grade> GradeConfirmByNavigations { get; set; } = new List<Grade>();

    public virtual ICollection<GradeRound> GradeRoundCoLecturers { get; set; } = new List<GradeRound>();

    public virtual ICollection<GradeRound> GradeRoundLecturers { get; set; } = new List<GradeRound>();

    public virtual ICollection<Grade> GradeStudents { get; set; } = new List<Grade>();

    public virtual ICollection<RegradeRequest> RegradeRequests { get; set; } = new List<RegradeRequest>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}